# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200516_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='waktu_posting',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
